#!/bin/sh -e
### BEGIN INIT INFO
# Provides:        bamboo
# Required-Start:    $remote_fs $network $ssh postgresql
# Required-Stop:    $remote_fs $network $ssh postgresql
# Default-Start:    2 3 4 5
# Default-Stop:        0 1 6
# Short-Description:    Bamboo
### END INIT INFO                  

# bamboo startup script
#chkconfig: 2345 80 05
#description: bamboo
 
# Define some variables
# Name of app ( bamboo, Confluence, etc )
APP=bamboo
# Name of the user to run as
USER=bamboo
# Location of application's bin directory
BASE=/opt/atlassian/bamboo
# Location of Java JDK
NAME=$APP

if [ -f "/lib/lsb/init-functions" ]; then
    . /lib/lsb/init-functions
else # this is for OS X where we do not have them, copy the jira to ~/bin
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
    . ${DIR}/lib/lsb/init-functions
fi

if [ -f /usr/libexec/java_home ]; then
export JAVA_HOME=$(/usr/libexec/java_home)
else
  # detect java location
  if [ -n "$JAVA_HOME" ]; then
    for JAVA_HOME in /usr/lib/jvm/java-7-oracle /usr/lib/jvm/java-6-sun /usr/lib/jvm/default-java /System/Library/Frameworks/JavaVM.framework/Home/
    do
        if [ -d "$JAVA_HOME" ]; then break ; fi
    done
  fi
  export JAVA_HOME
fi

case "$1" in
  # Start command
  start)
    echo "Starting $APP"
    /bin/su -m $USER -c "cd $BASE/logs && $BASE/bin/startup.sh &> /dev/null"
    ;;
  # Stop command
  stop)
    echo "Stopping $APP"
    /bin/su -m $USER -c "$BASE/bin/shutdown.sh &> /dev/null"
    echo "$APP stopped successfully"
    ;;
   # Restart command
   restart)
        $0 stop
        sleep 5
        $0 start
        ;;
    status)
        status_of_proc -p $ROOT_DIR/../work/catalina.pid "java" "$NAME" && exit 0 || exit $?
        ;;
  *)
    echo "Usage: /etc/init.d/$APP {start|restart|stop|status}"
    exit 1
    ;;
esac
 
exit 0