#!/bin/bash
# Crowd startup script
#chkconfig: 2345 80 05
#description: Crowd
 
 
# Based on script at http://www.bifrost.org/problems.html
 
RUN_AS_USER=root
CATALINA_HOME=/opt/crowd/apache-tomcat

function get_PID() {
    PID=`ps -A -o pid,command |grep java|grep "$CATALINA_HOME"|awk '{print $1}'`
}

start() {
        echo "Starting Crowd: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/bin/startup.sh"
        else
          $CATALINA_HOME/bin/startup.sh
        fi
        echo "done."
}
stop() {
        echo "Shutting down Crowd: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/bin/shutdown.sh"
        else
          $CATALINA_HOME/bin/shutdown.sh
        fi
        sleep 5
        get_PID
        if [ -n "$PID" ]; then
            log_progress_msg " killing $PID "
            kill -9 $PID
        fi
        echo "done."
}
 
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac
 
exit 0
