#!/bin/bash
# Crowd startup script
### BEGIN INIT INFO
# Provides:          crowd
# Required-Start:    $local_fs $network postgresql
# Required-Stop:     $local_fs postgresql
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: crowd
# Description:       crowd daemon
### END INIT INFO
#chkconfig: 2345 80 05
#description: Crowd
 
 
# Based on script at http://www.bifrost.org/problems.html
 
RUN_AS_USER=crowd
CATALINA_HOME=/opt/crowd/apache-tomcat

if [ -e /etc/debian_version ]; then
    . /lib/lsb/init-functions
elif [ -e /etc/init.d/functions ] ; then
    . /etc/init.d/functions
fi

for CATALINA_HOME in /opt/crowd/apache-tomcat /opt/atlassian/crowd/apache-tomcat
do
    if [ -d "$CATALINA_HOME" ]; then break ; fi
done
if [[ ! -e "$CATALINA_HOME/bin/startup.sh" ]] ; then
  echo "FATAL: Unable to detect install directory."
  exit 1
fi

function get_PID() {
    PID=`ps -A -o pid,command |grep java|grep "$CATALINA_HOME"|awk '{print $1}'`
}

start() {
        echo "Starting Crowd: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/bin/startup.sh"
        else
          $CATALINA_HOME/bin/startup.sh
        fi
        echo "done."
}
stop() {
        echo "Shutting down Crowd: "
        if [ "x$USER" != "x$RUN_AS_USER" ]; then
          su - $RUN_AS_USER -c "$CATALINA_HOME/bin/shutdown.sh"
        else
          $CATALINA_HOME/bin/shutdown.sh
        fi
        sleep 5
        get_PID
        if [ -n "$PID" ]; then
            log_progress_msg " killing $PID "
            kill -9 $PID
        fi
        echo "done."
}
 
case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart)
        stop
        start
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
esac
 
exit 0
