#!/usr/bin/env python
import os
import sys
import inspect
from optparse import OptionParser

cmd_folder = os.path.abspath(os.path.join(os.path.split(inspect.getfile(inspect.currentframe()))[0], "packages"))
if cmd_folder not in sys.path:
    sys.path.insert(0, cmd_folder)

from packages import jira
#from packages import jira
from packages.jira.config import get_jira

if __name__ == "__main__":

    parser = OptionParser()
    parser.add_option("--profile", dest="profile", default=None,
                      help="Which jira profile to load from config.ini, defauls to None")

    (options, args) = parser.parse_args()
    if len(args) != 2:
        sys.exit("You need to specify olduser and newuser.")

    j = jira.config.get_jira(profile=options.profile)

    print j.rename_user(args[0], args[1])
